name: Selenium Tests with Firefox

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          maven-version: '3.8.6'  # Use a recent version of Maven

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Pull Selenium Docker image
        run: docker pull selenium/standalone-firefox:latest

      - name: Verify Docker image
        run: docker run --rm selenium/standalone-firefox:latest firefox --version

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Display Surefire XML report
        if: always()
        run: |
          echo "Contents of Surefire XML report (testng-results.xml):"
          cat target/surefire-reports/testng-results.xml || echo "Surefire XML report not found."

      - name: Extract test results
        id: extract_results
        run: |
          total_tests=$(xmlstarlet sel -t -v "/testng-results/@total" target/surefire-reports/testng-results.xml)
          failed_tests=$(xmlstarlet sel -t -v "/testng-results/@failed" target/surefire-reports/testng-results.xml)
          skipped_tests=$(xmlstarlet sel -t -v "/testng-results/@skipped" target/surefire-reports/testng-results.xml)
          passed_tests=$(xmlstarlet sel -t -v "/testng-results/@passed" target/surefire-reports/testng-results.xml)
          echo "total=$total_tests" >> $GITHUB_ENV
          echo "failed=$failed_tests" >> $GITHUB_ENV
          echo "skipped=$skipped_tests" >> $GITHUB_ENV
          echo "passed=$passed_tests" >> $GITHUB_ENV

      - name: Display test results summary
        if: always()
        run: |
          echo "Total test cases = ${{ env.total }}"
          echo "Passed test cases = ${{ env.passed }}"
          echo "Failed test cases = ${{ env.failed }}"

      - name: Generate Markdown table
        id: generate_markdown_table
        run: |
          echo "### Test Results:" > markdown_table.md
          echo "### Passed Test Cases:" >> markdown_table.md
          xmlstarlet sel -t -m "//test-method[@status='PASS' and not(@name=preceding::test-method[@status='PASS']/@name)]" -v "@name" -n target/surefire-reports/testng-results.xml >> markdown_table.md
          echo "------------------------------" >> markdown_table.md
          echo "### Failed Test Cases:" >> markdown_table.md
          failed_tests=$(xmlstarlet sel -t -v "count(//test-method[@status='FAIL'])" target/surefire-reports/testng-results.xml)
          if [ "$failed_tests" -gt 0 ]; then
            xmlstarlet sel -t -m "//test-method[@status='FAIL' and not(@name=preceding::test-method[@status='FAIL']/@name)]" -v "@name" -n target/surefire-reports/testng-results.xml >> markdown_table.md
          else
            echo "No failed test cases." >> markdown_table.md
          fi

      - name: Upload Surefire XML report as artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload Markdown table as artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: markdown_table.md
